apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-alpine-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-alpine-app2
  template:
    metadata:
      labels:
        app: node-alpine-app2
    spec:
      containers:
      - name: node-alpine-container2
        image: adildot68/node-argocd2:1.0  # Adjust the image name
        ports:
        - containerPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: node-alpine-service2
spec:
  selector:
    app: node-alpine-app2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8008
  type: NodePort
